version: "3.3"
services:
  rutty:
    restart: always
    image: yantene/rutty
    build:
      context: .
      args:
        RAILS_ENV: development
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - .:/opt/www/rutty
    depends_on:
      - redis
      - dind
    environment:
      REDIS_URL: "redis://redis:6379"
      DOCKER_HOST: "tcp://dind:2375"
  redis:
    image: redis:6.0.10-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  dind:
    image: docker:20.10.2-dind
    healthcheck:
      test: ["CMD-SHELL", "docker run --rm hello-world || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 2
    environment:
      DOCKER_TLS_CERTDIR: ""
    privileged: true
